### ISSUE TITLE
Unable to Install 

### ISSUE THREAD

**Issue by sujanstha2052** [lonnieezell/Bonfire2#44]
Hi, I have been using Bonfire (1) for some years. And since I found out the Bonfire2 is in development with CI4. I was thinking of giving it a try. But the problem is I am unable to install it using the installation method provide. 
01. The database connection seems to have issue
![Capture](https://user-images.githubusercontent.com/47308970/146647759-3c4c4899-c785-4ca6-84e5-c4e4df63641e.PNG)

02. if I try to manually migrate there is issue. No tables found.

Is there any way to try Bonfire2. Am I doing anything wrong during the installation process.

**Comment by lonnieezell** [comment]
My guess would be to try using `127.0.0.1` instead of `localhost` for the database host.

**Comment by jeffstoner** [comment]
MySQL treats "localhost" very differently from "127.0.0.1". They are _not_ the same when it comes to MySQL access.

'Non-TCP (socket file, named pipe, and shared memory) connections are treated as local connections and match a host part of localhost if there are any such accounts, or host parts with wildcards that match localhost otherwise (for example, local%, l%, %).'  ref: https://dev.mysql.com/doc/refman/8.0/en/connection-access.html

So, 'user@localhost' and 'user@127.0.0.1' are two separate accounts in MySQL.

You need to check your permissions in MySQL and see what the account is, then match it when setting up Bonfire.

**Comment by sujanstha2052** [comment]
Thanks for the reply. I tried changing "localhost" to "127.0.0.1" but it still didn't work. I was able to install it by copying the "env" file to ".env" and adding the database information from the start. Then running the "php spark bf:install" command.
